listener 1883
allow_anonymous false
password_file /mosquitto/data/passwd
acl_file /mosquitto/data/acl
persistence true
persistence_location /mosquitto/data/
log_dest stdout
message_size_limit 16384
max_queued_messages 1000
